# Generated by Django 4.1.3 on 2023-01-19 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('urunler', '0006_serino_urun_seri'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='olusturan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='urun',
            name='seri',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='urunler.serino'),
        ),
    ]
