# Generated by Django 4.1.3 on 2023-02-21 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0009_odeme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odeme',
            name='sepet',
            field=models.ManyToManyField(to='urunler.sepet'),
        ),
    ]
